Fix a small typo
hugocaillard/clearness pull request #3
Opened 2022-03-22 22:35 UTC by moodmosaic

2022-03-22 22:35 UTC, moodmosaic commented
Great work, btw! :heart:

2022-03-23 13:37 UTC, hugocaillard requested changes
Hey @moodmosaic 
Thanks so much for the PR, I realised that this line was actually full of typos so made a quick review 👍

2022-03-23 13:37 UTC, hugocaillard commented on app/routes/__posts/00-annexes/03-coding-style.md
> +It ok to write functions on one line when they are short. IT's also ok to write them on multiple lines if you find it more consistent.
```suggestion
It's ok to write functions on one line when they are short. It's also ok to write them on multiple lines if you find it more consistent.
```

2022-03-23 14:09 UTC, moodmosaic commented
Great! Included in this PR is also the suggestion you added. Should be good to go (I guess) :eyes:

2022-03-23 14:24 UTC, hugocaillard approved these changes

2022-03-23 14:25 UTC, merged

2022-03-23 14:25 UTC, hugocaillard commented
Thanks a lot @moodmosaic. It makes you the first contributor on this project 😀

2022-03-23 14:26 UTC, moodmosaic commented
:tada: